<?php

declare(strict_types=1);

namespace Xestify\services;

use Xestify\validation\DefaultFieldValidatorRegistryFactory;
use Xestify\validation\FieldValidatorRegistry;
use Xestify\validation\model\ValidationError;
use Xestify\validation\model\ValidationResult;
use Xestify\validation\schema\SchemaFieldExtractor;
use Xestify\validation\support\ValidationRules;

final class ValidationService
{
    public function __construct(
        private ?SchemaFieldExtractor $fieldExtractor = null,
        private ?FieldValidatorRegistry $validatorRegistry = null,
        private ?ValidationRules $rules = null
    ) {
        $this->fieldExtractor ??= new SchemaFieldExtractor();
        $this->validatorRegistry ??= (new DefaultFieldValidatorRegistryFactory())->create();
        $this->rules ??= new ValidationRules();
    }

    public function validate(array $data, array $schema, bool $requireAll = true): ValidationResult
    {
        $errors = [];
        $knownFields = $this->fieldExtractor->extract($schema);

        foreach ($knownFields as $fieldName => $fieldRules) {
            $errors = array_merge($errors, $this->validateField($fieldName, $data, $fieldRules, $requireAll));
        }

        $errors = array_merge($errors, $this->validateNoUnknownFields($data, $knownFields, $schema));

        return $errors === []
            ? ValidationResult::valid()
            : ValidationResult::fromErrors($errors);
    }

    /**
     * Reject any key in $data that the schema does not declare.
     * `relations` keys are allowed through unchecked (DECISION 6: their
     * existence/type is a hook concern, not ValidationService's).
     *
     * @param array<string, mixed> $data
     * @param array<string, array<string, mixed>> $knownFields
     * @param array<string, mixed> $schema
     * @return list<ValidationError>
     */
    private function validateNoUnknownFields(array $data, array $knownFields, array $schema): array
    {
        $allowed = [...array_keys($knownFields), ...$this->relationKeys($schema)];
        $errors = [];

        foreach (array_keys($data) as $fieldName) {
            if (in_array($fieldName, $allowed, true)) {
                continue;
            }
            $errors[] = new ValidationError((string) $fieldName, 'unknown_field', 'Unknown field: ' . $fieldName);
        }

        return $errors;
    }

    /**
     * @param array<string, mixed> $schema
     * @return list<string>
     */
    private function relationKeys(array $schema): array
    {
        $relations = $schema['relations'] ?? [];
        if (!is_array($relations)) {
            return [];
        }

        $keys = [];
        foreach ($relations as $relationName => $definition) {
            if (is_string($relationName)) {
                $keys[] = $relationName;
            } elseif (is_array($definition) && is_string($definition['key'] ?? null)) {
                $keys[] = $definition['key'];
            }
        }

        return $keys;
    }

    /**
     * @param array<string, mixed> $data
     * @param array<string, mixed> $fieldRules
     * @return list<ValidationError>
     */
    private function validateField(string $fieldName, array $data, array $fieldRules, bool $requireAll): array
    {
        // A server-resolved field's final value never comes from the client
        // (ExtensionPluginContentService::resolveAutoGeneratedValue() and
        // equivalent entity-side resolution overwrite it), so whatever the
        // client sends — present, absent, wrong format — has no bearing on
        // the persisted value. Skipping it here (rather than dropping it
        // from SchemaFieldExtractor::extract()) keeps it in `knownFields`,
        // so validateNoUnknownFields() still allows the key through instead
        // of flagging it as unexpected.
        if ($this->isServerResolved($fieldRules)) {
            return [];
        }

        $isPresent = array_key_exists($fieldName, $data);
        $value = $isPresent ? $data[$fieldName] : null;

        if ($requireAll && $this->rules->isRequired($fieldRules) && $this->rules->isMissing($isPresent, $value)) {
            return [new ValidationError($fieldName, 'required', 'Field is required')];
        }

        if (!$this->shouldValidateValue($isPresent, $value)) {
            return [];
        }

        return $this->validatePresentValue($fieldName, $value, $fieldRules);
    }

    /** @param array<string, mixed> $fieldRules */
    private function isServerResolved(array $fieldRules): bool
    {
        return ($fieldRules['auto_generated'] ?? false) === true
            || ($fieldRules['auto_populated'] ?? false) === true;
    }

    private function shouldValidateValue(bool $isPresent, mixed $value): bool
    {
        return $isPresent && $value !== null && $value !== '';
    }

    /**
     * @param array<string, mixed> $fieldRules
     * @return list<ValidationError>
     */
    private function validatePresentValue(string $fieldName, mixed $value, array $fieldRules): array
    {
        $type = is_string($fieldRules['type'] ?? null) ? $fieldRules['type'] : 'string';
        $validator = $this->validatorRegistry->get($type);

        if ($validator === null) {
            return [new ValidationError($fieldName, 'unknown_type', 'Unsupported type: ' . $type)];
        }

        $errors = $validator->validate($fieldName, $value, $fieldRules);
        if ($errors !== []) {
            return $errors;
        }

        return $this->validateCommonRules($fieldName, $value, $fieldRules, $type);
    }

    /**
     * @param array<string, mixed> $fieldRules
     * @return list<ValidationError>
     */
    private function validateCommonRules(string $fieldName, mixed $value, array $fieldRules, string $type): array
    {
        if ($type === 'number') {
            return $this->rules->validateNumericBounds($fieldName, (float) $value, $fieldRules);
        }

        if ($this->usesStringBounds($type)) {
            return $this->rules->validateStringBounds($fieldName, (string) $value, $fieldRules);
        }

        return [];
    }

    private function usesStringBounds(string $type): bool
    {
        return in_array($type, ['string', 'text', 'mail', 'phone', 'date', 'timestamp', 'select'], true);
    }
}
