<?php

declare(strict_types=1);

namespace Xestify\controllers;

use PDO;
use Xestify\core\Request;
use Xestify\plugins\schema\PluginSchemaFieldNormalizer;
use Xestify\services\ValidationService;
use Xestify\validation\model\ValidationResult;

final class ExtensionPluginContentService
{
    public function __construct(private PDO $pdo, private ?ValidationService $validator = null)
    {
        $this->validator ??= new ValidationService();
    }

    /**
     * Validates $data against the extension's own schema (`fields` +
     * `relations`), same rules entity records already get via
     * EntityService::createRecord()/updateRecord() — extension plugins had
     * no server-side validation at all before this (PluginExtensionController
     * never called ValidationService), so `min`/`max`/`required` declared in
     * schema.json.fields were silently unenforced. Relation keys pass through
     * unchecked (DECISION 6, ValidationService.php).
     *
     * @param array<string, mixed> $data
     */
    public function validate(string $pluginSlug, array $data, bool $requireAll = true): ValidationResult
    {
        $schema = $this->loadExtensionSchema($pluginSlug);

        return $this->validator->validate($data, $schema, $requireAll);
    }

    /**
     * @param array<string, mixed> $data
     * @return array<string, mixed>
     */
    public function normalizeContentBySchema(string $pluginSlug, array $data, Request $request, bool $isUpdate = false): array
    {
        $schema = $this->loadExtensionSchema($pluginSlug);
        $fields = PluginSchemaFieldNormalizer::normalize($schema['fields'] ?? null) ?? [];
        $relationKeys = $this->relationKeys($schema);
        if ($fields === [] && $relationKeys === []) {
            return $data;
        }

        $normalized = [];
        foreach ($fields as $key => $definition) {
            if ($isUpdate && $key === 'author_id' && $this->isAutoGeneratedField($definition)) {
                // Authorship is set once at creation and must stay immutable on update.
                continue;
            }

            if (array_key_exists($key, $data)) {
                $normalized[$key] = $data[$key];
            }

            if ($this->isAutoGeneratedField($definition)) {
                $normalized[$key] = $this->resolveAutoGeneratedValue($key, $definition, $data, $request);
            }
        }

        // Relations carry no auto-generation/immutability rules of their own
        // (DECISION 6 — ValidationService already lets their keys through
        // unchecked, same as entity relations); just pass the value through
        // when present, same as any other plain field.
        foreach ($relationKeys as $key) {
            if (array_key_exists($key, $data)) {
                $normalized[$key] = $data[$key];
            }
        }

        return $normalized;
    }

    /**
     * @param array<string, mixed> $schema
     * @return list<string>
     */
    private function relationKeys(array $schema): array
    {
        $relations = $schema['relations'] ?? [];
        if (!is_array($relations)) {
            return [];
        }

        $keys = [];
        foreach ($relations as $relation) {
            if (is_array($relation) && is_string($relation['key'] ?? null) && $relation['key'] !== '') {
                $keys[] = $relation['key'];
            }
        }

        return $keys;
    }

    public function isEntityAllowedByPluginConfig(string $pluginSlug, string $entity): bool
    {
        $schema = $this->loadExtensionSchema($pluginSlug);
        $target = trim((string) ($schema['target_entity'] ?? '*'));
        if ($target === '' || $target === '*') {
            return true;
        }

        return $target === $entity;
    }

    /**
     * @return array<string, mixed> schema_json fields plus target_entity, merged
     *   in from manifest_json (STORY 10.3 §2bis — target_entity lives there, not
     *   in schema_json), so callers keep reading $schema['target_entity'] as before.
     */
    private function loadExtensionSchema(string $pluginSlug): array
    {
        $stmt = $this->pdo->prepare(
            "SELECT schema_json, manifest_json
               FROM plugins
              WHERE slug = :slug
                AND manifest_json->>'type' = 'extension'
              LIMIT 1"
        );
        $stmt->execute([':slug' => $pluginSlug]);
        $row = $stmt->fetch(PDO::FETCH_ASSOC);
        if ($row === false) {
            return [];
        }

        $decodedSchema = json_decode((string) ($row['schema_json'] ?? ''), true);
        $schema = is_array($decodedSchema) ? $decodedSchema : [];

        $decodedManifest = json_decode((string) ($row['manifest_json'] ?? ''), true);
        if (is_array($decodedManifest) && isset($decodedManifest['target_entity'])) {
            $schema['target_entity'] = $decodedManifest['target_entity'];
        }

        return $schema;
    }

    /**
     * @param array<string, mixed> $definition
     */
    private function isAutoGeneratedField(array $definition): bool
    {
        return ($definition['auto_generated'] ?? false) === true
            || ($definition['auto_populated'] ?? false) === true;
    }

    /**
     * @param array<string, mixed> $definition
     * @param array<string, mixed> $payload
     */
    private function resolveAutoGeneratedValue(string $key, array $definition, array $payload, Request $request): mixed
    {
        $value = $payload[$key] ?? null;

        if ($key === 'stamp') {
            $value = date('c');
        }

        if ($key === 'author_id') {
            $user = $request->user() ?? [];
            $subject = trim((string) ($user['sub'] ?? ''));
            if ($subject !== '') {
                $value = $subject;
            } else {
                $fallback = trim((string) ($payload['author_id'] ?? ''));
                $value = $fallback !== '' ? $fallback : null;
            }
        }

        if ($key !== 'stamp' && $key !== 'author_id') {
            $default = $definition['default'] ?? null;
            if ($default === 'now') {
                $value = date('c');
            } elseif ($default !== null) {
                $value = $default;
            }
        }

        return $value;
    }
}
