<?php

declare(strict_types=1);

namespace Xestify\controllers;

use PDO;
use Xestify\core\Request;
use Xestify\plugins\schema\PluginSchemaFieldNormalizer;

final class ExtensionPluginContentService
{
    public function __construct(private PDO $pdo)
    {
    }

    /**
     * @param array<string, mixed> $data
     * @return array<string, mixed>
     */
    public function normalizeContentBySchema(string $pluginSlug, array $data, Request $request, bool $isUpdate = false): array
    {
        $schema = $this->loadExtensionSchema($pluginSlug);
        $fields = PluginSchemaFieldNormalizer::normalize($schema['fields'] ?? null) ?? [];
        if ($fields === []) {
            return $data;
        }

        $normalized = [];
        foreach ($fields as $key => $definition) {
            if ($isUpdate && $key === 'author_id' && $this->isAutoGeneratedField($definition)) {
                // Authorship is set once at creation and must stay immutable on update.
                continue;
            }

            if (array_key_exists($key, $data)) {
                $normalized[$key] = $data[$key];
            }

            if ($this->isAutoGeneratedField($definition)) {
                $normalized[$key] = $this->resolveAutoGeneratedValue($key, $definition, $data, $request);
            }
        }

        return $normalized;
    }

    public function isEntityAllowedByPluginConfig(string $pluginSlug, string $entity): bool
    {
        $schema = $this->loadExtensionSchema($pluginSlug);
        $target = trim((string) ($schema['target_entity'] ?? '*'));
        if ($target === '' || $target === '*') {
            return true;
        }

        return $target === $entity;
    }

    /**
     * @return array<string, mixed>
     */
    private function loadExtensionSchema(string $pluginSlug): array
    {
        $stmt = $this->pdo->prepare(
            "SELECT schema_json
               FROM plugins
              WHERE slug = :slug
                AND plugin_type = 'extension'
              LIMIT 1"
        );
        $stmt->execute([':slug' => $pluginSlug]);
        $row = $stmt->fetch(PDO::FETCH_ASSOC);
        if ($row === false) {
            return [];
        }

        $decoded = json_decode((string) ($row['schema_json'] ?? ''), true);

        return is_array($decoded) ? $decoded : [];
    }

    /**
     * @param array<string, mixed> $definition
     */
    private function isAutoGeneratedField(array $definition): bool
    {
        return ($definition['auto_generated'] ?? false) === true
            || ($definition['auto_populated'] ?? false) === true;
    }

    /**
     * @param array<string, mixed> $definition
     * @param array<string, mixed> $payload
     */
    private function resolveAutoGeneratedValue(string $key, array $definition, array $payload, Request $request): mixed
    {
        $value = $payload[$key] ?? null;

        if ($key === 'stamp') {
            $value = date('c');
        }

        if ($key === 'author_id') {
            $user = $request->user() ?? [];
            $subject = trim((string) ($user['sub'] ?? ''));
            if ($subject !== '') {
                $value = $subject;
            } else {
                $fallback = trim((string) ($payload['author_id'] ?? ''));
                $value = $fallback !== '' ? $fallback : null;
            }
        }

        if ($key !== 'stamp' && $key !== 'author_id') {
            $default = $definition['default'] ?? null;
            if ($default === 'now') {
                $value = date('c');
            } elseif ($default !== null) {
                $value = $default;
            }
        }

        return $value;
    }
}
